
title: LAW SIMPLE
author: Lawsimple
description: "Ignorance of the law is no excuse."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lawsimple.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# Add your google-analytics ID here to activate google analytics
google_analytics: G-D4742KNMF3 # out your google-analytics code
contact_form_action: https://formspree.io/f/xvodrkzl
comments: true
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
permalink: none

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Lawsimple"

#gems: jekyll-feed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock