backend:
  name: git-gateway
  branch: master
  identity_url: "https://lawsimple.github.io/.netlify/identity"
  gateway_url: "https://lawsimple.github.io/.netlify/git"
  squash_merges: true

#publish_mode: editorial_workflow
media_folder: "img/uploads"

collections:
  - name: "workflow_settings"
    label: "Workflow Settings"
    files:
      - label: "Website settings"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Home Title"
            name: "home_title"
            widget: "string"