backend:
  name: git-gateway
  branch: master


#publish_mode: editorial_workflow
media_folder: "img/uploads"

collections:
  - name: 'Pages'
    label: 'pages'
    files:
      - label: 'Home Page'
        name: 'home_page'
        file: '_data/home.yml'
        fields:
          - label: 'Homepage Slider'
            name: 'homepage_slider'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Sub Title', name: 'subtitle', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Background Image', name: 'background_image', widget: 'image' }