backend:
  name: github
  repo: lawsimple/lawsimple.github.io
  branch: master
  open_authoring: true

# This line should *not* be indented
publish_mode: editorial_workflow

# Media files will be stored in the repo under images/uploads
media_folder: "img/uploads"

collections:
  - name: "home-settings" # Used in routes, e.g., /admin/collections/blog
    label: "Home Settings" # Used in the UI
    files:
      - label: "Home Settings"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: Title
            name: "home_title"
            widget: "string"
          - label: Description
            name: "home_description"
            widget: "string"

